// Generated by scripts/i18n/generate.ts. Do not edit.

use super::NativeExpr;

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum Locale {
    #[default]
    ZhCn,
    EnUs,
}

pub const SOURCE_LOCALE: Locale = Locale::ZhCn;

impl Locale {
    pub fn from_tag(raw: Option<&str>) -> Self {
        match raw.map(str::trim) {
            Some(value) if value.eq_ignore_ascii_case("zh-CN") => Self::ZhCn,
            Some(value) if value.eq_ignore_ascii_case("en-US") => Self::EnUs,
            Some(value) if !value.is_empty() => {
                eprintln!("[i18n] unsupported locale {value:?}; falling back to zh-CN");
                SOURCE_LOCALE
            }
            _ => SOURCE_LOCALE,
        }
    }

    pub fn tag(self) -> &'static str {
        match self {
            Self::ZhCn => "zh-CN",
            Self::EnUs => "en-US",
        }
    }
}

#[cfg(test)]
pub(super) const RUSSIAN_CARDINAL_CASES: &[(i64, &str)] = &[
    (0_i64, "many"),
    (1_i64, "one"),
    (2_i64, "few"),
    (5_i64, "many"),
    (11_i64, "many"),
    (21_i64, "one"),
    (22_i64, "few"),
    (25_i64, "many"),
];

#[cfg(test)]
#[rustfmt::skip]
pub(super) const RUSSIAN_CARDINAL_MESSAGE: NativeExpr = NativeExpr::Plural { arg: "count", cases: &[("few", NativeExpr::Concat(&[NativeExpr::Arg("count"), NativeExpr::Literal(":few")])), ("many", NativeExpr::Concat(&[NativeExpr::Arg("count"), NativeExpr::Literal(":many")])), ("one", NativeExpr::Concat(&[NativeExpr::Arg("count"), NativeExpr::Literal(":one")])), ("other", NativeExpr::Concat(&[NativeExpr::Arg("count"), NativeExpr::Literal(":other")]))] };

#[rustfmt::skip]
pub(super) fn lookup(locale: Locale, key: &str) -> Option<NativeExpr> {
    match (locale, key) {
        (Locale::ZhCn, "native.category.ai") => Some(NativeExpr::Literal("AI")),
        (Locale::ZhCn, "native.category.browser") => Some(NativeExpr::Literal("浏览器")),
        (Locale::ZhCn, "native.category.communication") => Some(NativeExpr::Literal("沟通")),
        (Locale::ZhCn, "native.category.design") => Some(NativeExpr::Literal("设计")),
        (Locale::ZhCn, "native.category.development") => Some(NativeExpr::Literal("开发")),
        (Locale::ZhCn, "native.category.game") => Some(NativeExpr::Literal("游戏")),
        (Locale::ZhCn, "native.category.music") => Some(NativeExpr::Literal("音乐")),
        (Locale::ZhCn, "native.category.office") => Some(NativeExpr::Literal("办公")),
        (Locale::ZhCn, "native.category.other") => Some(NativeExpr::Literal("其他")),
        (Locale::ZhCn, "native.category.system") => Some(NativeExpr::Literal("系统")),
        (Locale::ZhCn, "native.category.utility") => Some(NativeExpr::Literal("工具")),
        (Locale::ZhCn, "native.category.video") => Some(NativeExpr::Literal("视频")),
        (Locale::ZhCn, "native.export.duration") => Some(NativeExpr::Concat(&[NativeExpr::Plural { arg: "hours", cases: &[("other", NativeExpr::Concat(&[NativeExpr::Arg("hours"), NativeExpr::Literal(" 小时")]))] }, NativeExpr::Literal(" "), NativeExpr::Plural { arg: "minutes", cases: &[("other", NativeExpr::Concat(&[NativeExpr::Arg("minutes"), NativeExpr::Literal(" 分钟")]))] }])),
        (Locale::ZhCn, "native.export.empty") => Some(NativeExpr::Literal("所选范围内没有活动记录。")),
        (Locale::ZhCn, "native.export.exportedAt") => Some(NativeExpr::Concat(&[NativeExpr::Literal("导出时间："), NativeExpr::Arg("value"), NativeExpr::Literal("")])),
        (Locale::ZhCn, "native.export.field.app_name") => Some(NativeExpr::Literal("应用名称")),
        (Locale::ZhCn, "native.export.field.browser_client_id") => Some(NativeExpr::Literal("浏览器客户端 ID")),
        (Locale::ZhCn, "native.export.field.browser_exe_name") => Some(NativeExpr::Literal("浏览器可执行文件")),
        (Locale::ZhCn, "native.export.field.browser_kind") => Some(NativeExpr::Literal("浏览器类型")),
        (Locale::ZhCn, "native.export.field.category") => Some(NativeExpr::Literal("分类")),
        (Locale::ZhCn, "native.export.field.category_color") => Some(NativeExpr::Literal("分类颜色")),
        (Locale::ZhCn, "native.export.field.category_id") => Some(NativeExpr::Literal("分类 ID")),
        (Locale::ZhCn, "native.export.field.continuity_group_start_time") => Some(NativeExpr::Literal("连续组开始时间")),
        (Locale::ZhCn, "native.export.field.created_at") => Some(NativeExpr::Literal("创建时间")),
        (Locale::ZhCn, "native.export.field.domain") => Some(NativeExpr::Literal("域名")),
        (Locale::ZhCn, "native.export.field.duration_minutes") => Some(NativeExpr::Literal("时长（分钟）")),
        (Locale::ZhCn, "native.export.field.duration_ms") => Some(NativeExpr::Literal("时长（毫秒）")),
        (Locale::ZhCn, "native.export.field.end_time") => Some(NativeExpr::Literal("结束时间")),
        (Locale::ZhCn, "native.export.field.exe_name") => Some(NativeExpr::Literal("可执行文件名")),
        (Locale::ZhCn, "native.export.field.favicon_url") => Some(NativeExpr::Literal("网站图标 URL")),
        (Locale::ZhCn, "native.export.field.local_date") => Some(NativeExpr::Literal("本地日期")),
        (Locale::ZhCn, "native.export.field.local_month") => Some(NativeExpr::Literal("本地月份")),
        (Locale::ZhCn, "native.export.field.local_week") => Some(NativeExpr::Literal("本地周")),
        (Locale::ZhCn, "native.export.field.normalized_domain") => Some(NativeExpr::Literal("标准化域名")),
        (Locale::ZhCn, "native.export.field.page_title") => Some(NativeExpr::Literal("页面标题")),
        (Locale::ZhCn, "native.export.field.record_type") => Some(NativeExpr::Literal("记录类型")),
        (Locale::ZhCn, "native.export.field.session_id") => Some(NativeExpr::Literal("会话 ID")),
        (Locale::ZhCn, "native.export.field.source_key") => Some(NativeExpr::Literal("来源键")),
        (Locale::ZhCn, "native.export.field.source_name") => Some(NativeExpr::Literal("来源名称")),
        (Locale::ZhCn, "native.export.field.start_hour") => Some(NativeExpr::Literal("开始小时")),
        (Locale::ZhCn, "native.export.field.start_time") => Some(NativeExpr::Literal("开始时间")),
        (Locale::ZhCn, "native.export.field.unknown") => Some(NativeExpr::Literal("未知字段")),
        (Locale::ZhCn, "native.export.field.updated_at") => Some(NativeExpr::Literal("更新时间")),
        (Locale::ZhCn, "native.export.field.url") => Some(NativeExpr::Literal("URL 地址")),
        (Locale::ZhCn, "native.export.field.web_segment_id") => Some(NativeExpr::Literal("网页片段 ID")),
        (Locale::ZhCn, "native.export.field.web_source") => Some(NativeExpr::Literal("网页来源")),
        (Locale::ZhCn, "native.export.field.weekday") => Some(NativeExpr::Literal("星期")),
        (Locale::ZhCn, "native.export.field.window_title") => Some(NativeExpr::Literal("窗口标题")),
        (Locale::ZhCn, "native.export.range") => Some(NativeExpr::Concat(&[NativeExpr::Literal("导出范围："), NativeExpr::Arg("start"), NativeExpr::Literal(" 至 "), NativeExpr::Arg("end"), NativeExpr::Literal("")])),
        (Locale::ZhCn, "native.export.rangeAll") => Some(NativeExpr::Literal("全部")),
        (Locale::ZhCn, "native.export.rangeCurrent") => Some(NativeExpr::Literal("当前")),
        (Locale::ZhCn, "native.export.records") => Some(NativeExpr::Plural { arg: "count", cases: &[("other", NativeExpr::Concat(&[NativeExpr::Literal("记录数量："), NativeExpr::Arg("count")]))] }),
        (Locale::ZhCn, "native.export.title") => Some(NativeExpr::Literal("Patina 活动记录")),
        (Locale::ZhCn, "native.export.totalDuration") => Some(NativeExpr::Concat(&[NativeExpr::Literal("总时长："), NativeExpr::Arg("value"), NativeExpr::Literal("")])),
        (Locale::ZhCn, "native.tools.activityReminderAppTitle") => Some(NativeExpr::Literal("应用提醒")),
        (Locale::ZhCn, "native.tools.activityReminderCategoryTitle") => Some(NativeExpr::Literal("分类提醒")),
        (Locale::ZhCn, "native.tools.activityReminderDefaultBody") => Some(NativeExpr::Concat(&[NativeExpr::Arg("targetName"), NativeExpr::Literal(" 今日已活动 "), NativeExpr::Plural { arg: "usageMinutes", cases: &[("other", NativeExpr::Concat(&[NativeExpr::Arg("usageMinutes"), NativeExpr::Literal(" 分钟")]))] }, NativeExpr::Literal("，已达到 "), NativeExpr::Plural { arg: "limitMinutes", cases: &[("other", NativeExpr::Concat(&[NativeExpr::Arg("limitMinutes"), NativeExpr::Literal(" 分钟上限")]))] }])),
        (Locale::ZhCn, "native.tools.activityReminderWebTitle") => Some(NativeExpr::Literal("网页提醒")),
        (Locale::ZhCn, "native.tools.breakEnded") => Some(NativeExpr::Literal("休息结束")),
        (Locale::ZhCn, "native.tools.countdownDefaultBody") => Some(NativeExpr::Literal("倒计时已完成")),
        (Locale::ZhCn, "native.tools.countdownTitle") => Some(NativeExpr::Literal("倒计时结束")),
        (Locale::ZhCn, "native.tools.focusEnded") => Some(NativeExpr::Literal("专注结束")),
        (Locale::ZhCn, "native.tools.nextFocus") => Some(NativeExpr::Literal("下一阶段：专注")),
        (Locale::ZhCn, "native.tools.nextLongBreak") => Some(NativeExpr::Literal("下一阶段：长休息")),
        (Locale::ZhCn, "native.tools.nextShortBreak") => Some(NativeExpr::Literal("下一阶段：短休息")),
        (Locale::ZhCn, "native.tools.reminderDefaultBody") => Some(NativeExpr::Literal("时间到了")),
        (Locale::ZhCn, "native.tools.reminderTitle") => Some(NativeExpr::Literal("提醒")),
        (Locale::ZhCn, "native.tray.disableTitle") => Some(NativeExpr::Literal("屏蔽标题")),
        (Locale::ZhCn, "native.tray.enableTitle") => Some(NativeExpr::Literal("记录标题")),
        (Locale::ZhCn, "native.tray.pause") => Some(NativeExpr::Literal("暂停追踪")),
        (Locale::ZhCn, "native.tray.quit") => Some(NativeExpr::Literal("退出应用")),
        (Locale::ZhCn, "native.tray.resume") => Some(NativeExpr::Literal("恢复追踪")),
        (Locale::ZhCn, "native.tray.showMain") => Some(NativeExpr::Literal("打开主界面")),
        (Locale::EnUs, "native.category.ai") => Some(NativeExpr::Literal("AI")),
        (Locale::EnUs, "native.category.browser") => Some(NativeExpr::Literal("Browser")),
        (Locale::EnUs, "native.category.communication") => Some(NativeExpr::Literal("Communication")),
        (Locale::EnUs, "native.category.design") => Some(NativeExpr::Literal("Design")),
        (Locale::EnUs, "native.category.development") => Some(NativeExpr::Literal("Development")),
        (Locale::EnUs, "native.category.game") => Some(NativeExpr::Literal("Game")),
        (Locale::EnUs, "native.category.music") => Some(NativeExpr::Literal("Music")),
        (Locale::EnUs, "native.category.office") => Some(NativeExpr::Literal("Office")),
        (Locale::EnUs, "native.category.other") => Some(NativeExpr::Literal("Other")),
        (Locale::EnUs, "native.category.system") => Some(NativeExpr::Literal("System")),
        (Locale::EnUs, "native.category.utility") => Some(NativeExpr::Literal("Utility")),
        (Locale::EnUs, "native.category.video") => Some(NativeExpr::Literal("Video")),
        (Locale::EnUs, "native.export.duration") => Some(NativeExpr::Concat(&[NativeExpr::Plural { arg: "hours", cases: &[("one", NativeExpr::Concat(&[NativeExpr::Arg("hours"), NativeExpr::Literal("h")])), ("other", NativeExpr::Concat(&[NativeExpr::Arg("hours"), NativeExpr::Literal("h")]))] }, NativeExpr::Literal(" "), NativeExpr::Plural { arg: "minutes", cases: &[("one", NativeExpr::Concat(&[NativeExpr::Arg("minutes"), NativeExpr::Literal("m")])), ("other", NativeExpr::Concat(&[NativeExpr::Arg("minutes"), NativeExpr::Literal("m")]))] }])),
        (Locale::EnUs, "native.export.empty") => Some(NativeExpr::Literal("No activity records were found in the selected range.")),
        (Locale::EnUs, "native.export.exportedAt") => Some(NativeExpr::Concat(&[NativeExpr::Literal("Exported at: "), NativeExpr::Arg("value"), NativeExpr::Literal("")])),
        (Locale::EnUs, "native.export.field.app_name") => Some(NativeExpr::Literal("App Name")),
        (Locale::EnUs, "native.export.field.browser_client_id") => Some(NativeExpr::Literal("Browser Client ID")),
        (Locale::EnUs, "native.export.field.browser_exe_name") => Some(NativeExpr::Literal("Browser Executable")),
        (Locale::EnUs, "native.export.field.browser_kind") => Some(NativeExpr::Literal("Browser Kind")),
        (Locale::EnUs, "native.export.field.category") => Some(NativeExpr::Literal("Category")),
        (Locale::EnUs, "native.export.field.category_color") => Some(NativeExpr::Literal("Category Color")),
        (Locale::EnUs, "native.export.field.category_id") => Some(NativeExpr::Literal("Category ID")),
        (Locale::EnUs, "native.export.field.continuity_group_start_time") => Some(NativeExpr::Literal("Continuity Group Start")),
        (Locale::EnUs, "native.export.field.created_at") => Some(NativeExpr::Literal("Created At")),
        (Locale::EnUs, "native.export.field.domain") => Some(NativeExpr::Literal("Domain")),
        (Locale::EnUs, "native.export.field.duration_minutes") => Some(NativeExpr::Literal("Duration (minutes)")),
        (Locale::EnUs, "native.export.field.duration_ms") => Some(NativeExpr::Literal("Duration (ms)")),
        (Locale::EnUs, "native.export.field.end_time") => Some(NativeExpr::Literal("End Time")),
        (Locale::EnUs, "native.export.field.exe_name") => Some(NativeExpr::Literal("Executable Name")),
        (Locale::EnUs, "native.export.field.favicon_url") => Some(NativeExpr::Literal("Favicon URL")),
        (Locale::EnUs, "native.export.field.local_date") => Some(NativeExpr::Literal("Local Date")),
        (Locale::EnUs, "native.export.field.local_month") => Some(NativeExpr::Literal("Local Month")),
        (Locale::EnUs, "native.export.field.local_week") => Some(NativeExpr::Literal("Local Week")),
        (Locale::EnUs, "native.export.field.normalized_domain") => Some(NativeExpr::Literal("Normalized Domain")),
        (Locale::EnUs, "native.export.field.page_title") => Some(NativeExpr::Literal("Page Title")),
        (Locale::EnUs, "native.export.field.record_type") => Some(NativeExpr::Literal("Record Type")),
        (Locale::EnUs, "native.export.field.session_id") => Some(NativeExpr::Literal("Session ID")),
        (Locale::EnUs, "native.export.field.source_key") => Some(NativeExpr::Literal("Source Key")),
        (Locale::EnUs, "native.export.field.source_name") => Some(NativeExpr::Literal("Source Name")),
        (Locale::EnUs, "native.export.field.start_hour") => Some(NativeExpr::Literal("Start Hour")),
        (Locale::EnUs, "native.export.field.start_time") => Some(NativeExpr::Literal("Start Time")),
        (Locale::EnUs, "native.export.field.unknown") => Some(NativeExpr::Literal("Unknown Field")),
        (Locale::EnUs, "native.export.field.updated_at") => Some(NativeExpr::Literal("Updated At")),
        (Locale::EnUs, "native.export.field.url") => Some(NativeExpr::Literal("URL")),
        (Locale::EnUs, "native.export.field.web_segment_id") => Some(NativeExpr::Literal("Web Segment ID")),
        (Locale::EnUs, "native.export.field.web_source") => Some(NativeExpr::Literal("Web Source")),
        (Locale::EnUs, "native.export.field.weekday") => Some(NativeExpr::Literal("Weekday")),
        (Locale::EnUs, "native.export.field.window_title") => Some(NativeExpr::Literal("Window Title")),
        (Locale::EnUs, "native.export.range") => Some(NativeExpr::Concat(&[NativeExpr::Literal("Range: "), NativeExpr::Arg("start"), NativeExpr::Literal(" to "), NativeExpr::Arg("end"), NativeExpr::Literal("")])),
        (Locale::EnUs, "native.export.rangeAll") => Some(NativeExpr::Literal("All")),
        (Locale::EnUs, "native.export.rangeCurrent") => Some(NativeExpr::Literal("Current")),
        (Locale::EnUs, "native.export.records") => Some(NativeExpr::Plural { arg: "count", cases: &[("one", NativeExpr::Concat(&[NativeExpr::Literal("Record: "), NativeExpr::Arg("count")])), ("other", NativeExpr::Concat(&[NativeExpr::Literal("Records: "), NativeExpr::Arg("count")]))] }),
        (Locale::EnUs, "native.export.title") => Some(NativeExpr::Literal("Patina Activity Records")),
        (Locale::EnUs, "native.export.totalDuration") => Some(NativeExpr::Concat(&[NativeExpr::Literal("Total duration: "), NativeExpr::Arg("value"), NativeExpr::Literal("")])),
        (Locale::EnUs, "native.tools.activityReminderAppTitle") => Some(NativeExpr::Literal("App reminder")),
        (Locale::EnUs, "native.tools.activityReminderCategoryTitle") => Some(NativeExpr::Literal("Category reminder")),
        (Locale::EnUs, "native.tools.activityReminderDefaultBody") => Some(NativeExpr::Concat(&[NativeExpr::Arg("targetName"), NativeExpr::Literal(" has been active for "), NativeExpr::Plural { arg: "usageMinutes", cases: &[("one", NativeExpr::Concat(&[NativeExpr::Arg("usageMinutes"), NativeExpr::Literal(" minute")])), ("other", NativeExpr::Concat(&[NativeExpr::Arg("usageMinutes"), NativeExpr::Literal(" minutes")]))] }, NativeExpr::Literal(", reaching the "), NativeExpr::Plural { arg: "limitMinutes", cases: &[("one", NativeExpr::Concat(&[NativeExpr::Arg("limitMinutes"), NativeExpr::Literal("-minute daily limit")])), ("other", NativeExpr::Concat(&[NativeExpr::Arg("limitMinutes"), NativeExpr::Literal("-minute daily limit")]))] }])),
        (Locale::EnUs, "native.tools.activityReminderWebTitle") => Some(NativeExpr::Literal("Web reminder")),
        (Locale::EnUs, "native.tools.breakEnded") => Some(NativeExpr::Literal("Break complete")),
        (Locale::EnUs, "native.tools.countdownDefaultBody") => Some(NativeExpr::Literal("The countdown is complete")),
        (Locale::EnUs, "native.tools.countdownTitle") => Some(NativeExpr::Literal("Countdown finished")),
        (Locale::EnUs, "native.tools.focusEnded") => Some(NativeExpr::Literal("Focus complete")),
        (Locale::EnUs, "native.tools.nextFocus") => Some(NativeExpr::Literal("Next: focus")),
        (Locale::EnUs, "native.tools.nextLongBreak") => Some(NativeExpr::Literal("Next: long break")),
        (Locale::EnUs, "native.tools.nextShortBreak") => Some(NativeExpr::Literal("Next: short break")),
        (Locale::EnUs, "native.tools.reminderDefaultBody") => Some(NativeExpr::Literal("Time is up")),
        (Locale::EnUs, "native.tools.reminderTitle") => Some(NativeExpr::Literal("Reminder")),
        (Locale::EnUs, "native.tray.disableTitle") => Some(NativeExpr::Literal("Block titles")),
        (Locale::EnUs, "native.tray.enableTitle") => Some(NativeExpr::Literal("Record titles")),
        (Locale::EnUs, "native.tray.pause") => Some(NativeExpr::Literal("Pause tracking")),
        (Locale::EnUs, "native.tray.quit") => Some(NativeExpr::Literal("Exit Patina")),
        (Locale::EnUs, "native.tray.resume") => Some(NativeExpr::Literal("Resume tracking")),
        (Locale::EnUs, "native.tray.showMain") => Some(NativeExpr::Literal("Open main window")),
        _ => None,
    }
}
