import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";
import {
  FRONTEND_GENERATED_ROOT,
  LOCALES_ROOT,
  RUST_GENERATED_PATH,
  loadAndValidateProductionLocales,
  schemaEntriesBySurface,
  sourceLocale,
  stableStringify,
  type MessageDescriptor,
  type MessageValue,
  type SchemaEntry,
} from "./core.ts";
import { LOCALE_REGISTRY } from "../../locales/registry.ts";
import { MESSAGE_SCHEMA } from "../../locales/schema.ts";
import { MESSAGES as RUSSIAN_FIXTURE } from "../../locales/fixtures/ru-RU/plurals.ts";

interface TypeTree {
  leaf?: string;
  children: Map<string, TypeTree>;
}

function buildUiTextType(entries: Array<[string, SchemaEntry]>): string {
  const root: TypeTree = { children: new Map() };
  for (const [key, entry] of entries) {
    const segments = key.split(".");
    let cursor = root;
    for (const segment of segments) {
      let child = cursor.children.get(segment);
      if (!child) {
        child = { children: new Map() };
        cursor.children.set(segment, child);
      }
      cursor = child;
    }
    if (entry.kind === "string") cursor.leaf = "string";
    else if (entry.kind === "string-array") cursor.leaf = "string[]";
    else if (entry.kind === "string-record") cursor.leaf = "Record<string | number, string>";
    else if (entry.kind === "data" && "resultType" in entry && typeof entry.resultType === "string") cursor.leaf = entry.resultType;
    else {
      const params = entry.params.map((param) => `${param.name}${param.optional ? "?" : ""}: ${param.type === "integer" ? "number" : param.type}`).join(", ");
      cursor.leaf = `(${params}) => string`;
    }
  }
  const render = (node: TypeTree, indent: string): string => {
    if (node.leaf) return node.leaf;
    const lines = [...node.children].sort(([left], [right]) => left.localeCompare(right)).map(([key, child]) => `${indent}${JSON.stringify(key)}: ${render(child, `${indent}  `)};`);
    return `{\n${lines.join("\n")}\n${indent.slice(2)}}`;
  };
  return `export interface UiText ${render(root, "  ")}\n`;
}

export function compactFrontendValue(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(compactFrontendValue);
  if (!value || typeof value !== "object") return value;
  const record = value as Record<string, unknown>;
  if (record.$op === "concat" && Array.isArray(record.parts)) {
    const parts = record.parts.filter((part) => part !== "").map(compactFrontendValue);
    return { ...record, parts };
  }
  return Object.fromEntries(Object.entries(record).map(([key, child]) => [key, compactFrontendValue(child)]));
}

function frontendResourceValues(
  messages: Record<string, MessageValue>,
  frontendEntries: Array<[string, SchemaEntry]>,
): unknown[] {
  return frontendEntries.map(([key, entry]) => {
    const value = messages[key];
    return compactFrontendValue(entry.kind === "message" ? (value as MessageDescriptor).body : value);
  });
}

function renderFrontendLocaleResources(
  messages: Record<string, MessageValue>,
  frontendEntries: Array<[string, SchemaEntry]>,
): string {
  return `// Generated by scripts/i18n/generate.ts. Do not edit.\nexport const FRONTEND_LOCALE_RESOURCES = ${JSON.stringify(frontendResourceValues(messages, frontendEntries))} as const;\n`;
}

function renderFrontendResources(allMessages: Record<string, Record<string, MessageValue>>): string {
  const frontendEntries = schemaEntriesBySurface("frontend");
  const keys = frontendEntries.map(([key]) => key);
  const parameterLists = frontendEntries.map(([, entry]) => (
    entry.kind === "message" ? entry.params.map((param) => param.name) : undefined
  ));
  const lastParameterIndex = parameterLists.map(Boolean).lastIndexOf(true);
  const params = parameterLists
    .slice(0, lastParameterIndex + 1)
    .map((value) => value ? JSON.stringify(value) : "")
    .join(",");
  const canonicalSourceLocale = sourceLocale();
  const loaders = Object.keys(allMessages).map((locale) => (
    locale === canonicalSourceLocale
      ? `  ${JSON.stringify(locale)}: () => Promise.resolve(FRONTEND_SOURCE_RESOURCES),`
      : `  ${JSON.stringify(locale)}: () => import(${JSON.stringify(`./locales/${locale}.ts`)}).then((module) => module.FRONTEND_LOCALE_RESOURCES),`
  )).join("\n");
  return `// Generated by scripts/i18n/generate.ts. Do not edit.\nimport type { Locale } from "./contract.ts";\nimport { FRONTEND_LOCALE_RESOURCES as FRONTEND_SOURCE_RESOURCES } from ${JSON.stringify(`./locales/${canonicalSourceLocale}.ts`)};\n\nexport const SOURCE_LOCALE = ${JSON.stringify(canonicalSourceLocale)} as const satisfies Locale;\nexport { FRONTEND_SOURCE_RESOURCES };\nexport const FRONTEND_MESSAGE_KEYS = ${JSON.stringify(keys)} as const;\nexport const FRONTEND_MESSAGE_PARAMS = [${params}] as const;\n\nexport const FRONTEND_LOCALE_LOADERS = {\n${loaders}\n} as const satisfies Record<Locale, () => Promise<readonly unknown[]>>;\n`;
}

function rustString(value: string): string {
  return JSON.stringify(value).replaceAll("\\u2028", "\\u{2028}").replaceAll("\\u2029", "\\u{2029}");
}

function rustLocaleVariant(locale: string): string {
  return locale.split(/[^A-Za-z0-9]+/).map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1).toLowerCase()}`).join("");
}

function renderRustExpression(expression: unknown): string {
  if (typeof expression === "string") return `NativeExpr::Literal(${rustString(expression)})`;
  if (!expression || typeof expression !== "object" || Array.isArray(expression)) throw new Error("Native messages only support string expression nodes");
  const node = expression as Record<string, unknown>;
  if (node.$op === "arg" && typeof node.name === "string") return `NativeExpr::Arg(${rustString(node.name)})`;
  if (node.$op === "concat" && Array.isArray(node.parts)) {
    return `NativeExpr::Concat(&[${node.parts.map(renderRustExpression).join(", ")}])`;
  }
  if (node.$op === "plural" && typeof node.arg === "string" && node.cases && typeof node.cases === "object" && !Array.isArray(node.cases)) {
    const cases = Object.entries(node.cases as Record<string, unknown>)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([category, value]) => `(${rustString(category)}, ${renderRustExpression(value)})`)
      .join(", ");
    return `NativeExpr::Plural { arg: ${rustString(node.arg)}, cases: &[${cases}] }`;
  }
  throw new Error(`Native generated message uses unsupported op ${String(node.$op)}`);
}

function nativeExpression(value: MessageValue): string {
  if (typeof value === "string") return renderRustExpression(value);
  if (value && typeof value === "object" && !Array.isArray(value) && (value as MessageDescriptor).$type === "message") {
    return renderRustExpression((value as MessageDescriptor).body);
  }
  throw new Error("Native message must be a string or supported expression descriptor");
}

function renderRustResources(allMessages: Record<string, Record<string, MessageValue>>): string {
  const nativeKeys = schemaEntriesBySurface("native").map(([key]) => key).sort();
  const arms: string[] = [];
  for (const locale of Object.keys(LOCALE_REGISTRY)) {
    const variant = `Locale::${rustLocaleVariant(locale)}`;
    for (const key of nativeKeys) {
      arms.push(`        (${variant}, ${rustString(key)}) => Some(${nativeExpression(allMessages[locale][key])}),`);
    }
  }
  const russianCases = (RUSSIAN_FIXTURE["fixture.cases"] as readonly string[]).map((entry) => {
    const [value, category] = entry.split(":");
    return `    (${value}_i64, ${rustString(category)}),`;
  }).join("\n");
  const russianMessage = RUSSIAN_FIXTURE["fixture.cardinal"] as MessageDescriptor;
  const locales = Object.keys(LOCALE_REGISTRY);
  const canonicalSourceLocale = sourceLocale();
  const variants = locales.map((locale) => `    ${locale === canonicalSourceLocale ? "#[default]\n    " : ""}${rustLocaleVariant(locale)},`).join("\n");
  const parsers = locales.map((locale) => `            Some(value) if value.eq_ignore_ascii_case(${rustString(locale)}) => Self::${rustLocaleVariant(locale)},`).join("\n");
  const tags = locales.map((locale) => `            Self::${rustLocaleVariant(locale)} => ${rustString(locale)},`).join("\n");
  return `// Generated by scripts/i18n/generate.ts. Do not edit.\n\nuse super::NativeExpr;\n\n#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]\npub enum Locale {\n${variants}\n}\n\npub const SOURCE_LOCALE: Locale = Locale::${rustLocaleVariant(canonicalSourceLocale)};\n\nimpl Locale {\n    pub fn from_tag(raw: Option<&str>) -> Self {\n        match raw.map(str::trim) {\n${parsers}\n            Some(value) if !value.is_empty() => {\n                eprintln!("[i18n] unsupported locale {value:?}; falling back to ${canonicalSourceLocale}");\n                SOURCE_LOCALE\n            }\n            _ => SOURCE_LOCALE,\n        }\n    }\n\n    pub fn tag(self) -> &'static str {\n        match self {\n${tags}\n        }\n    }\n}\n\n#[cfg(test)]\npub(super) const RUSSIAN_CARDINAL_CASES: &[(i64, &str)] = &[\n${russianCases}\n];\n\n#[cfg(test)]\n#[rustfmt::skip]\npub(super) const RUSSIAN_CARDINAL_MESSAGE: NativeExpr = ${renderRustExpression(russianMessage.body)};\n\n#[rustfmt::skip]\npub(super) fn lookup(locale: Locale, key: &str) -> Option<NativeExpr> {\n    match (locale, key) {\n${arms.join("\n")}\n        _ => None,\n    }\n}\n`;
}

function expectedFiles(allMessages: Record<string, Record<string, MessageValue>>): Record<string, string> {
  const frontendEntries = schemaEntriesBySurface("frontend");
  const files: Record<string, string> = {
    [join(FRONTEND_GENERATED_ROOT, "contract.ts")]: `// Generated by scripts/i18n/generate.ts. Do not edit.\nexport const SUPPORTED_LOCALES = ${JSON.stringify(Object.keys(LOCALE_REGISTRY))} as const;\nexport type Locale = (typeof SUPPORTED_LOCALES)[number];\nexport const LOCALE_METADATA = ${JSON.stringify(LOCALE_REGISTRY, null, 2)} as const satisfies Record<Locale, { label: string; source: boolean; direction: "ltr" | "rtl"; production: boolean }>;\n\n${buildUiTextType(schemaEntriesBySurface("frontend"))}`,
    [join(FRONTEND_GENERATED_ROOT, "resources.ts")]: renderFrontendResources(allMessages),
    [RUST_GENERATED_PATH]: renderRustResources(allMessages),
  };
  for (const [locale, messages] of Object.entries(allMessages)) {
    files[join(FRONTEND_GENERATED_ROOT, "locales", `${locale}.ts`)] = renderFrontendLocaleResources(messages, frontendEntries);
  }
  return files;
}

function staleGeneratedLocaleFiles(expectedPaths: ReadonlySet<string>): string[] {
  const localeRoot = join(FRONTEND_GENERATED_ROOT, "locales");
  if (!existsSync(localeRoot)) return [];
  return readdirSync(localeRoot)
    .filter((file) => file.endsWith(".ts"))
    .map((file) => join(localeRoot, file))
    .filter((path) => !expectedPaths.has(path));
}

export async function generateI18n(write: boolean): Promise<void> {
  const messages = await loadAndValidateProductionLocales();
  const files = expectedFiles(messages);
  const expectedPaths = new Set(Object.keys(files));
  const extraLocaleFiles = staleGeneratedLocaleFiles(expectedPaths);
  const stale: string[] = [];
  if (write) {
    for (const path of extraLocaleFiles) rmSync(path);
  } else {
    stale.push(...extraLocaleFiles);
  }
  for (const [path, content] of Object.entries(files)) {
    if (write) {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, content, "utf8");
    } else {
      let current = "";
      try { current = readFileSync(path, "utf8"); } catch { /* reported as stale */ }
      if (current !== content) stale.push(path);
    }
  }
  if (stale.length > 0) throw new Error(`Generated i18n output is stale:\n${stale.join("\n")}\nRun npm run i18n:generate.`);
  if (write) console.log(`Generated ${Object.keys(MESSAGE_SCHEMA).length} locale contract entries from ${LOCALES_ROOT}`);
  else console.log(`i18n contract and generated output are current (${stableStringify(Object.keys(files))})`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await generateI18n(process.argv.includes("--write"));
}
